/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import Entity.HoaDon.HoaDonXemDuLieu;
import Entity.KhachHang.KhachHang;
import Repository.ChonKhachHangRepository;
import Repository.DonHangChiTietRepository;
import Repository.HoaDonrepository;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import java.sql.*;
import KetNoiSQL.ketnoi;
/**
 *
 * @author SingPC
 */
public class ChonKhachHangBanHang extends javax.swing.JFrame {
private ChonKhachHangRepository kh = new ChonKhachHangRepository();
private DefaultTableModel md = new DefaultTableModel();
  private DonHangChiTietRepository dh = new DonHangChiTietRepository();
    /**
     * Creates new form ChonKhachHangBanHang
     */
    public ChonKhachHangBanHang() {
        
        initComponents();
        hienThiLuaChoKhachHangg(kh.layThongTinKhachHang());
    }
           private void hienThiLuaChoKhachHangg(ArrayList<KhachHang> khachHang){
        md = (DefaultTableModel) tblthemkhachhang.getModel();
        md.setRowCount(0);
        for (KhachHang khachHang1 : khachHang) {
            md.addRow(new Object[]{
                khachHang1.getMaKH(), khachHang1.getTenKH(), khachHang1.getEmail(),khachHang1.getSDT(),khachHang1.getDiaChi(), khachHang1.isGioiTinh()?"Nam":"Nữ", khachHang1.isTrangThai()?"Đang Hoạt Động":"Ngừng Hoạt Đông"
            });
        }
    }
    
    private KhachHang getFomat(){
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtmaKhachHang.getText());
        kh.setTenKH(txttenkahchhang.getText());
        kh.setEmail(txtemail.getText());
        kh.setSDT(txtsodienthaoi.getText());
        kh.setDiaChi(txtdiachi.getText());
        boolean gioiTinh = rdoNam.isSelected();
        kh.setGioiTinh(gioiTinh);
        boolean trangThaii = rdoDangHoatDong.isSelected();
        kh.setTrangThai(trangThaii);
        return kh;
    }
    private void add(){
        kh.addThongTinKhachHang(getFomat());
        hienThiLuaChoKhachHangg(kh.layThongTinKhachHang());
    }
    private void hienThiDuLieuLenTextFile(int index){
        KhachHang sc = kh.layThongTinKhachHang().get(index);
        txtmaKhachHang.setText(sc.getMaKH());
        txttenkahchhang.setText(sc.getTenKH());
        txtemail.setText(sc.getEmail());
        txtsodienthaoi.setText(sc.getSDT());
        txtdiachi.setText(sc.getDiaChi());
        if(sc.isGioiTinh()){
            rdoNam.setSelected(true);
        }else{
            rdoNu.setSelected(true);
        }
        if(sc.isTrangThai()){
            rdoDangHoatDong.setSelected(true);
        }else{
            rdoNgungHoatDong.setSelected(true);
        }
    }
    private void update(){
        KhachHang sc = getFomat();
        boolean ketQua = kh.updateThongTinKhachHang(sc, sc.getMaKH());
        if(ketQua){
            hienThiLuaChoKhachHangg(kh.layThongTinKhachHang());
        }else{
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        txttenkahchhang = new javax.swing.JTextField();
        txtsodienthaoi = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoDangHoatDong = new javax.swing.JRadioButton();
        rdoNgungHoatDong = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblthemkhachhang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtmaKhachHang = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 77, 287, -1));
        jPanel3.add(txttenkahchhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 77, 276, -1));
        jPanel3.add(txtsodienthaoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 133, 276, -1));

        buttonGroup2.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel3.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 209, 72, -1));

        buttonGroup2.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel3.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 209, 60, -1));

        buttonGroup1.add(rdoDangHoatDong);
        rdoDangHoatDong.setText("Đang Hoạt Động");
        jPanel3.add(rdoDangHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 167, -1, -1));

        buttonGroup1.add(rdoNgungHoatDong);
        rdoNgungHoatDong.setText("Ngừng Hoạt Động");
        jPanel3.add(rdoNgungHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 167, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("THÊM KHÁCH HÀNG MỚI");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 17, -1, 33));

        jLabel2.setText("Số Điện Thoại");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 111, 100, -1));

        jLabel3.setText("Tên Khách Hàng");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 55, 100, -1));

        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 56, 100, -1));

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane3.setViewportView(txtdiachi);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 133, 287, 97));

        jLabel5.setText("Địa Chỉ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 111, 54, -1));

        tblthemkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ", "Tên Khách Hàng", "Email", "Sô điện Thoại", "Địa Chỉ", "Giới Tính", "Trạng Thái"
            }
        ));
        tblthemkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthemkhachhangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblthemkhachhang);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 327, 598, 393));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 264, -1, -1));

        jButton2.setText("Xóa");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 264, -1, -1));

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 264, -1, -1));

        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 264, -1, -1));

        txtmaKhachHang.setText(" ");
        jPanel3.add(txtmaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 264, 114, 23));

        jLabel8.setText("Mã Khách Hàng");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 242, 124, 24));

        jButton7.setText("Làm Mới");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 264, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
              String soDienThoi = txtsodienthaoi.getText().trim();
    String sql = "SELECT COUNT(*) AS count FROM khachHang WHERE so_dien_thoai = ? ";
    try (Connection con = ketnoi.getConnection();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, soDienThoi);
        ResultSet rs = ps.executeQuery();

        if (rs.next() && rs.getInt("count") > 0) {
            // Nếu sản phẩm đã tồn tại
            JOptionPane.showMessageDialog(this, "Số Điện Thoại Đã Tồn Tại");
        } else {
             add();
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi kiểm tra tên sản phẩm");
    }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblthemkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthemkhachhangMouseClicked
        // TODO add your handling code here:
        int index = tblthemkhachhang.getSelectedRow();
        hienThiDuLieuLenTextFile(index);
    }//GEN-LAST:event_tblthemkhachhangMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
 public boolean capNhatKhachHang(int maHoaDon, int maKhachHang) {
int check = 0;
        String cauLenhSQL = "UPDATE DonHang SET ma_khach_hang = ? WHERE id_ma_don_hang = ?";
        try (Connection con = ketnoi.getConnection()){
             PreparedStatement lenh = con.prepareStatement(cauLenhSQL);
            lenh.setInt(1, maKhachHang);
            lenh.setInt(2, maHoaDon);
            check = lenh.executeUpdate();
            if (check > 0) {
//                hienThiDuLieu(dh.layHhoaDon());
                System.out.println("Cập nhật thành công!");
            } else {
                System.out.println("Không tìm thấy hóa đơn phù hợp!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    return check >0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonKhachHangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonKhachHangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonKhachHangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonKhachHangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonKhachHangBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rdoDangHoatDong;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNgungHoatDong;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblthemkhachhang;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtmaKhachHang;
    private javax.swing.JTextField txtsodienthaoi;
    private javax.swing.JTextField txttenkahchhang;
    // End of variables declaration//GEN-END:variables
}
