/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaoDien;

import Entity.DonHangChiTiet.DonHangChiTietEntity;
import Entity.HoaDon.HoaDonXemDuLieu;
import GiaoDien.HoaDonChiTiet;
import KetNoiSQL.ketnoi;
import Repository.DonHangChiTietRepository;
import Repository.HoaDonrepository;
import com.toedter.calendar.JCalendar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SingPC
 */
public class ChucNangHoaDon extends javax.swing.JPanel {
private HoaDonrepository hd = new HoaDonrepository();
private DefaultTableModel md = new DefaultTableModel();
private DonHangChiTietRepository ct = new DonHangChiTietRepository();

    /**
     * Creates new form ChucNangHoaDon
     */
    public ChucNangHoaDon() {
        initComponents();
        
        hienThiDuLieu(hd.getAllChiTietHoaDon());

    }
    public void hienThiDuLieu(ArrayList<HoaDonChiTiet> hoaDon){
        md = (DefaultTableModel) tbl_hoaDon.getModel();
        md.setRowCount(0);
        for (HoaDonChiTiet hoaDonXemDuLieu : hoaDon) {
            md.addRow(new Object[]{
                hoaDonXemDuLieu.getMaHoaDon(), hoaDonXemDuLieu.getTongTien(),hoaDonXemDuLieu.getThanhToan(),hoaDonXemDuLieu.getTienKhachDua(), hoaDonXemDuLieu.getTienTraKhach(), hoaDonXemDuLieu.getPhuongThuc(),hoaDonXemDuLieu.getNgayDat(), hoaDonXemDuLieu.getTrangThai()
            });
        }
    }
    public void hienThiDonHangChiTiet(ArrayList<DonHangChiTietEntity> chitiet){
        md = (DefaultTableModel)tbl_hoaDonChiTiet.getModel();
        md.setRowCount(0);
        for (DonHangChiTietEntity donHangChiTietEntity : chitiet) {
            md.addRow(new Object[]{
                donHangChiTietEntity.getMaSanPham(), donHangChiTietEntity.getTenSanPham(), donHangChiTietEntity.getSoLuong(), donHangChiTietEntity.getGiaBan(),donHangChiTietEntity.getTongTien(), donHangChiTietEntity.getTrangThai()
            });
        }
    }

private void TimKiem() {
    // Lấy dữ liệu từ các trường nhập liệu
    java.util.Date NgayBatDau = (Date) txtNgayBatDau.getDate();
    java.util.Date NgayKetThuc = (Date) txtNgayKetThuc.getDate();
    String trangThai = TrangThai.getSelectedItem().toString();  // Lấy trạng thái từ combobox
    String hinhThucThanhToan = hinhThuc.getSelectedItem().toString();  // Lấy phương thức thanh toán từ combobox
    String maHoaDon = txt_timKiemHoaDon.getText().trim();  // Lấy mã hóa đơn từ trường nhập liệu

    // Kiểm tra nếu người dùng không nhập mã hóa đơn
    if (maHoaDon.isEmpty()) {
        maHoaDon = ""; // Nếu trống, set về giá trị mặc định là chuỗi rỗng
    }

    // Chuyển đổi java.util.Date sang java.sql.Date
    java.sql.Date sqlNgayBatDau = (NgayBatDau != null) ? new java.sql.Date(NgayBatDau.getTime()) : null;
    java.sql.Date sqlNgayKetThuc = (NgayKetThuc != null) ? new java.sql.Date(NgayKetThuc.getTime()) : null;

    // Gọi phương thức timkiemSanPham() để tìm kiếm các hóa đơn chi tiết
    ArrayList<HoaDonChiTiet> kk = hd.timkiemSanPham(trangThai, hinhThucThanhToan, maHoaDon, sqlNgayBatDau, sqlNgayKetThuc);
    
    // Hiển thị kết quả tìm kiếm lên giao diện
    hienThiDuLieu(kk);
}



  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_HoaDon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_timKiemHoaDon = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoaDon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        hinhThuc = new javax.swing.JComboBox<>();
        TrangThai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_hoaDonChiTiet = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_HoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel_HoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm Kiếm Hoá Đơn:");
        jPanel_HoaDon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 40));

        txt_timKiemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemHoaDonActionPerformed(evt);
            }
        });
        txt_timKiemHoaDon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timKiemHoaDonKeyReleased(evt);
            }
        });
        jPanel_HoaDon.add(txt_timKiemHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 420, -1));

        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timKiem.setText("Tìm Kiếm");
        btn_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timKiemMouseClicked(evt);
            }
        });
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        jPanel_HoaDon.add(btn_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        tbl_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hoá Đơn", "Tổng Tiền", "Thanh Toán", "Tiền Khách Đưa", "Tiền Trả Khách", "Hình Thức Thanh Toán", "Ngày Lập Hoá Đơn", "Trạng Thái"
            }
        ));
        tbl_hoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hoaDon);

        jPanel_HoaDon.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, 1090, 210));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hình Thức Thanh Toán:");
        jPanel_HoaDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        hinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "            ", "Tiền Mặt", "Chuyển Khoản", "Cả hai" }));
        hinhThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinhThucActionPerformed(evt);
            }
        });
        jPanel_HoaDon.add(hinhThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 240, -1));

        TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                ", "Đang Chờ Thanh Toán", "Thanh Toán Thành Công", "Hủy Đơn Hàng" }));
        TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangThaiActionPerformed(evt);
            }
        });
        jPanel_HoaDon.add(TrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Trạng Thái Thanh Toán:");
        jPanel_HoaDon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        txtNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayKetThuc.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgayKetThucAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel_HoaDon.add(txtNgayKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 220, -1));

        txtNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayBatDau.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtNgayBatDauAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel_HoaDon.add(txtNgayBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 220, -1));

        tbl_hoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá Bán", "Tổng Tiền", "Trạng Thái"
            }
        ));
        jScrollPane3.setViewportView(tbl_hoaDonChiTiet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1091, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_hoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoaDonMouseClicked
        // TODO add your handling code here:
        int selectedRowHoaDon = tbl_hoaDon.getSelectedRow();
        if (selectedRowHoaDon != -1) {
            String maGioHangHienTai = tbl_hoaDon.getValueAt(selectedRowHoaDon, 0).toString();
            hienThiDonHangChiTiet(ct.getAll(maGioHangHienTai));
        }

    }//GEN-LAST:event_tbl_hoaDonMouseClicked

    private void TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangThaiActionPerformed
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_TrangThaiActionPerformed

    private void txtNgayBatDauAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgayBatDauAncestorAdded
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtNgayBatDauAncestorAdded

    private void txtNgayKetThucAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtNgayKetThucAncestorAdded
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtNgayKetThucAncestorAdded

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        TimKiem();
    
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void txt_timKiemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemHoaDonActionPerformed
        // TODO add your handling code here:
       TimKiem();
    }//GEN-LAST:event_txt_timKiemHoaDonActionPerformed

    private void btn_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timKiemMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btn_timKiemMouseClicked

    private void hinhThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinhThucActionPerformed
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_hinhThucActionPerformed

    private void txt_timKiemHoaDonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemHoaDonKeyReleased
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_txt_timKiemHoaDonKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TrangThai;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JComboBox<String> hinhThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel_HoaDon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_hoaDon;
    private javax.swing.JTable tbl_hoaDonChiTiet;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private javax.swing.JTextField txt_timKiemHoaDon;
    // End of variables declaration//GEN-END:variables
}
