/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import java.awt.Color;
import java.awt.Toolkit; 
import java.util.ArrayList;
public class TrangChu extends javax.swing.JFrame {
    public TrangChu() {
        initComponents();
             setTitle("Phầm Mềm Quản Lý Và Bán Hàng");
             setIconImage();
         ChuyenChucNang ccn = new ChuyenChucNang(manhinh);
         ccn.setView(txtbanhang1, txtbanhang);
         ArrayList<ChucNang> ls  = new ArrayList<>();
         ls.add(new ChucNang("ChucNangBanHang", txtbanhang1,txtbanhang ));
         ls.add(new ChucNang("ChucNangSanPham", txtsanpham1, txtsanpham));
         ls.add(new ChucNang("ChucNangHoaDon", txthoadon1, txthoadon));
         ls.add(new ChucNang("FomtestBanHnag", txtbanhang1, txtbanhang));
         ls.add(new ChucNang("ChucNangThongKe", txtthongke1, txtthongke));
         ls.add(new ChucNang("ChucNangVouvher", txtvoucher1, txtvoucher));
         ls.add(new ChucNang("ChucNangKhachHang", txtkhachhang1, txtkhachhang));
          ls.add(new ChucNang("ChucNangNhanVien", txtnhanvien1, txtnhanvien));
         ccn.DuyEm(ls);
         hirnThiDuLieu();
    }
  public void hirnThiDuLieu(){
//        txtTenNhanvien.setText(luuThongTinDangNhap.getTenNhanVien());
        txtidnhanvien.setText(String.valueOf(LuuThongTinDangNhap.getInNhanVien()));
    }
    
    /**
         * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manhinh = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        banhang = new javax.swing.JLabel();
        txtbanhang = new javax.swing.JLabel();
        sanpham = new javax.swing.JLabel();
        txtsanpham = new javax.swing.JLabel();
        hoadon = new javax.swing.JLabel();
        txthoadon = new javax.swing.JLabel();
        voucher = new javax.swing.JLabel();
        txtvoucher = new javax.swing.JLabel();
        txtdoihang = new javax.swing.JLabel();
        doihang = new javax.swing.JLabel();
        txtkhachhang = new javax.swing.JLabel();
        khachhang = new javax.swing.JLabel();
        txtthongke = new javax.swing.JLabel();
        thongke = new javax.swing.JLabel();
        txtdangxuat = new javax.swing.JLabel();
        dangxuat = new javax.swing.JLabel();
        txtnhanvien = new javax.swing.JLabel();
        nhanvien = new javax.swing.JLabel();
        txtidnhanvien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbanhang1 = new javax.swing.JPanel();
        txtsanpham1 = new javax.swing.JPanel();
        txthoadon1 = new javax.swing.JPanel();
        txtvoucher1 = new javax.swing.JPanel();
        txtdoihang1 = new javax.swing.JPanel();
        txtkhachhang1 = new javax.swing.JPanel();
        txtthongke1 = new javax.swing.JPanel();
        txtdangxuat1 = new javax.swing.JPanel();
        txtnhanvien1 = new javax.swing.JPanel();
        txtbanhang27 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        manhinh.setBackground(new java.awt.Color(244, 239, 245));
        manhinh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout manhinhLayout = new javax.swing.GroupLayout(manhinh);
        manhinh.setLayout(manhinhLayout);
        manhinhLayout.setHorizontalGroup(
            manhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        manhinhLayout.setVerticalGroup(
            manhinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banhang.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        banhang.setForeground(new java.awt.Color(255, 255, 255));
        banhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/seller.png"))); // NOI18N
        banhang.setText("BÁN HÀNG");
        jPanel3.add(banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        txtbanhang.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 30));

        sanpham.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        sanpham.setForeground(new java.awt.Color(255, 255, 255));
        sanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SanPham.png"))); // NOI18N
        sanpham.setText("SẢN PHẨM");
        jPanel3.add(sanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        txtsanpham.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtsanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 30));

        hoadon.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        hoadon.setForeground(new java.awt.Color(255, 255, 255));
        hoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HoaDon.png"))); // NOI18N
        hoadon.setText("HÓA ĐƠN");
        jPanel3.add(hoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        txthoadon.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txthoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 30));

        voucher.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        voucher.setForeground(new java.awt.Color(255, 255, 255));
        voucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/GiamGia.png"))); // NOI18N
        voucher.setText("VOUCHER");
        jPanel3.add(voucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 30));

        txtvoucher.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtvoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 30));

        txtdoihang.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtdoihang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 30));

        doihang.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        doihang.setForeground(new java.awt.Color(255, 255, 255));
        doihang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/DoiHang.png"))); // NOI18N
        doihang.setText("Đổi hàng");
        jPanel3.add(doihang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 30));

        txtkhachhang.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 30));

        khachhang.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        khachhang.setForeground(new java.awt.Color(255, 255, 255));
        khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/KhachHang.png"))); // NOI18N
        khachhang.setText("khách hàng");
        jPanel3.add(khachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, 30));

        txtthongke.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 190, 30));

        thongke.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        thongke.setForeground(new java.awt.Color(255, 255, 255));
        thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ThongKe.png"))); // NOI18N
        thongke.setText("Thống kê");
        jPanel3.add(thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, 30));

        txtdangxuat.setForeground(new java.awt.Color(255, 255, 255));
        txtdangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdangxuatMouseClicked(evt);
            }
        });
        jPanel3.add(txtdangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 190, 30));

        dangxuat.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        dangxuat.setForeground(new java.awt.Color(255, 255, 255));
        dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Thoat.png"))); // NOI18N
        dangxuat.setText("Đăng xuất");
        jPanel3.add(dangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, 30));

        txtnhanvien.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 190, 30));

        nhanvien.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhanVien.png"))); // NOI18N
        nhanvien.setText("nhân viên");
        jPanel3.add(nhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, 30));

        txtidnhanvien.setText("  ");
        jPanel3.add(txtidnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rectangle 10 (12).png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 247, 760));

        txtbanhang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtbanhang1Layout = new javax.swing.GroupLayout(txtbanhang1);
        txtbanhang1.setLayout(txtbanhang1Layout);
        txtbanhang1Layout.setHorizontalGroup(
            txtbanhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtbanhang1Layout.setVerticalGroup(
            txtbanhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtbanhang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtsanpham1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtsanpham1Layout = new javax.swing.GroupLayout(txtsanpham1);
        txtsanpham1.setLayout(txtsanpham1Layout);
        txtsanpham1Layout.setHorizontalGroup(
            txtsanpham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtsanpham1Layout.setVerticalGroup(
            txtsanpham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtsanpham1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txthoadon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txthoadon1Layout = new javax.swing.GroupLayout(txthoadon1);
        txthoadon1.setLayout(txthoadon1Layout);
        txthoadon1Layout.setHorizontalGroup(
            txthoadon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txthoadon1Layout.setVerticalGroup(
            txthoadon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txthoadon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtvoucher1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtvoucher1Layout = new javax.swing.GroupLayout(txtvoucher1);
        txtvoucher1.setLayout(txtvoucher1Layout);
        txtvoucher1Layout.setHorizontalGroup(
            txtvoucher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtvoucher1Layout.setVerticalGroup(
            txtvoucher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtvoucher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtdoihang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtdoihang1Layout = new javax.swing.GroupLayout(txtdoihang1);
        txtdoihang1.setLayout(txtdoihang1Layout);
        txtdoihang1Layout.setHorizontalGroup(
            txtdoihang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtdoihang1Layout.setVerticalGroup(
            txtdoihang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtdoihang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtkhachhang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtkhachhang1Layout = new javax.swing.GroupLayout(txtkhachhang1);
        txtkhachhang1.setLayout(txtkhachhang1Layout);
        txtkhachhang1Layout.setHorizontalGroup(
            txtkhachhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtkhachhang1Layout.setVerticalGroup(
            txtkhachhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtkhachhang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        txtthongke1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtthongke1Layout = new javax.swing.GroupLayout(txtthongke1);
        txtthongke1.setLayout(txtthongke1Layout);
        txtthongke1Layout.setHorizontalGroup(
            txtthongke1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtthongke1Layout.setVerticalGroup(
            txtthongke1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtthongke1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        txtdangxuat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtdangxuat1Layout = new javax.swing.GroupLayout(txtdangxuat1);
        txtdangxuat1.setLayout(txtdangxuat1Layout);
        txtdangxuat1Layout.setHorizontalGroup(
            txtdangxuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtdangxuat1Layout.setVerticalGroup(
            txtdangxuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtdangxuat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        txtnhanvien1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtnhanvien1Layout = new javax.swing.GroupLayout(txtnhanvien1);
        txtnhanvien1.setLayout(txtnhanvien1Layout);
        txtnhanvien1Layout.setHorizontalGroup(
            txtnhanvien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtnhanvien1Layout.setVerticalGroup(
            txtnhanvien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtnhanvien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        txtbanhang27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout txtbanhang27Layout = new javax.swing.GroupLayout(txtbanhang27);
        txtbanhang27.setLayout(txtbanhang27Layout);
        txtbanhang27Layout.setHorizontalGroup(
            txtbanhang27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        txtbanhang27Layout.setVerticalGroup(
            txtbanhang27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.add(txtbanhang27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manhinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(manhinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdangxuatMouseClicked
        // TODO add your handling code here:
        dispose();
        DangNhapChinh duyem = new DangNhapChinh();
        duyem.setVisible(true);
    }//GEN-LAST:event_txtdangxuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }   
        });
    }
 private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Brown Simple Aesthetic Bag Store Logo 2.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banhang;
    private javax.swing.JLabel dangxuat;
    private javax.swing.JLabel doihang;
    private javax.swing.JLabel hoadon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel khachhang;
    private javax.swing.JPanel manhinh;
    private javax.swing.JLabel nhanvien;
    private javax.swing.JLabel sanpham;
    private javax.swing.JLabel thongke;
    private javax.swing.JLabel txtbanhang;
    private javax.swing.JPanel txtbanhang1;
    private javax.swing.JPanel txtbanhang27;
    private javax.swing.JLabel txtdangxuat;
    private javax.swing.JPanel txtdangxuat1;
    private javax.swing.JLabel txtdoihang;
    private javax.swing.JPanel txtdoihang1;
    private javax.swing.JLabel txthoadon;
    private javax.swing.JPanel txthoadon1;
    private javax.swing.JLabel txtidnhanvien;
    private javax.swing.JLabel txtkhachhang;
    private javax.swing.JPanel txtkhachhang1;
    private javax.swing.JLabel txtnhanvien;
    private javax.swing.JPanel txtnhanvien1;
    private javax.swing.JLabel txtsanpham;
    private javax.swing.JPanel txtsanpham1;
    private javax.swing.JLabel txtthongke;
    private javax.swing.JPanel txtthongke1;
    private javax.swing.JLabel txtvoucher;
    private javax.swing.JPanel txtvoucher1;
    private javax.swing.JLabel voucher;
    // End of variables declaration//GEN-END:variables

   
}
