/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import Entity.HoaDon.HoaDonEntity;
import Entity.HoaDon.XuatHoaDon;
import Repository.HoaDonrepository;
import Repository.XuatHoaDonRepository;
import com.itextpdf.io.font.PdfEncodings;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.TextAlignment;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;
import GiaoDien.JOptionPane;
import KetNoiSQL.ketnoi;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.layout.element.IBlockElement;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author SingPC
 */
public class XuatHoaDonnn extends javax.swing.JFrame {

    private XuatHoaDonRepository hd = new XuatHoaDonRepository();
    private DefaultTableModel md = new DefaultTableModel();

   
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng ngày tháng
   
    DecimalFormat formatterr = new DecimalFormat("###,###,###");

    /**
     * Creates new form NewJFrame
     */
    public XuatHoaDonnn() {
        initComponents();
        loadDuLieuu();
    }

    private void loadDuLieuu() {
        ArrayList<XuatHoaDon> hdList = hd.getAll();

        // Debug: Kiểm tra dữ liệu trả về
        System.out.println("Số lượng hóa đơn: " + hdList.size());
        if (!hdList.isEmpty()) {
            System.out.println("Dữ liệu hóa đơn đầu tiên: " + hdList.get(0).toString());

            XuatHoaDon firstOrder = hdList.get(0);
            nhanvien.setText(firstOrder.getTenNhanVien());
            txtmahoadon.setText(firstOrder.getMaHoaDon());
            txthotenkhachhang.setText(firstOrder.getTenKhachHang());
            txttensanpham.setText(firstOrder.getTenSanPham());
            soluong.setText(formatterr.format(firstOrder.getSoLuong())); 
            gia.setText(formatterr.format(firstOrder.getGiaBan()));     
            giamgia.setText(formatterr.format(firstOrder.getGiaTri()));  
            tongtien.setText(formatterr.format(firstOrder.getThanhTien())); 
            tienkhachdua.setText(formatterr.format(firstOrder.getTienKhachDua())); 
            tientrakhac.setText(formatterr.format(firstOrder.getTienTraKhach()));  
            thue.setText(formatterr.format(firstOrder.getThue()));        
            txtsodienthoaikhachhang.setText(firstOrder.getSoDienThoai());
            txtid.setText(String.valueOf(firstOrder.getIdHoaDon()));     
            phuongthucthanhtoan.setText(firstOrder.getPhuongThuc());
             String ngayTaoText = ngaytao.getText();
    ngaytao.setText(formatter.format(ngayTaoText)); 
        } else {
            nhanvien.setText("NULL");
            System.out.println("Danh sách hóa đơn trống.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        Email = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txttensanpham = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        soluong = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gia = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        giamgia = new javax.swing.JLabel();
        tongtien = new javax.swing.JLabel();
        tienkhachdua = new javax.swing.JLabel();
        tientrakhac = new javax.swing.JLabel();
        txthotenkhachhang = new javax.swing.JLabel();
        txtsodienthoaikhachhang = new javax.swing.JLabel();
        diachi = new javax.swing.JLabel();
        nhanvien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ngaytao = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtmahoadon = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        thue = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        XuatHoaDon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phuongthucthanhtoan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Email.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("THÔNG TIN HÓA ĐƠN");
        Email.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nhân viên");
        Email.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("THÔNG TIN KHÁCH HÀNG");
        Email.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 180, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Địa Chỉ");
        Email.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        Email.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Họ và tên");
        Email.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 210, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Số điện thoại");
        Email.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 252, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SẢN PHẨM");
        Email.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txttensanpham.setText(" ");
        Email.add(txttensanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 150, -1));

        jLabel14.setText("Áo polo");
        Email.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 60, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Số Lượng");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Giá");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        Email.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        soluong.setText(" ");
        Email.add(soluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jLabel16.setText("5");
        Email.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 15, -1));

        gia.setText(" ");
        Email.add(gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jLabel18.setText("10000 VĐN");
        Email.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        jLabel19.setText("Tiền Hàng ");
        Email.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel20.setText("Giảm Giá");
        Email.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel21.setText("Tổng Tiền");
        Email.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        jLabel23.setText("Tiền khách đưa");
        Email.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel24.setText("Tiền trả khách");
        Email.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 616, -1, 30));

        jLabel25.setText("10000 VĐN");
        Email.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, -1, -1));

        giamgia.setText(" ");
        Email.add(giamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        tongtien.setText(" ");
        Email.add(tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        tienkhachdua.setText(" ");
        Email.add(tienkhachdua, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, -1));

        tientrakhac.setText(" ");
        Email.add(tientrakhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, -1));

        txthotenkhachhang.setText(" ");
        Email.add(txthotenkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 232, 142, -1));

        txtsodienthoaikhachhang.setText("   ");
        Email.add(txtsodienthoaikhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 272, 142, -1));

        diachi.setText("   Hậu Ái, Vân Canh, Hoài Đức, Hà Nội");
        Email.add(diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, -1));

        nhanvien.setText(" ");
        Email.add(nhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 121, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày Tạo");
        Email.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 150, -1, -1));

        ngaytao.setText("   ");
        Email.add(ngaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 150, 85, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Mã Hóa Đơn");
        Email.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 116, -1, -1));

        txtmahoadon.setText("   ");
        Email.add(txtmahoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 116, 58, -1));

        jLabel32.setText("Thuế");
        Email.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 35, -1));

        thue.setText(" ");
        Email.add(thue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, -1, -1));

        txtemail.setText("doanngocduy62@gmaail.com");
        Email.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        XuatHoaDon.setText("Xuất Hóa Đơn");
        XuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatHoaDonActionPerformed(evt);
            }
        });
        Email.add(XuatHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        jButton2.setText("Quay Lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Email.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, -1, -1));

        txtid.setText(" ");
        Email.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 116, -1, -1));

        jLabel13.setText("Phương Thức Thanh Toán");
        Email.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, -1, -1));

        phuongthucthanhtoan.setText(" ");
        Email.add(phuongthucthanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Brown Simple Aesthetic Bag Store Logo 2.png"))); // NOI18N
        Email.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void XuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            // Tạo file PDF
            String filePath = "D:\\" + txtmahoadon.getText() + ".pdf";
            File file = new File(filePath);

            if (file.exists()) {
                file.delete(); // Xóa file nếu đã tồn tại
            }

            PdfWriter writer = new PdfWriter(file);
            PdfDocument pdf = new PdfDocument(writer);
            com.itextpdf.layout.Document document = new com.itextpdf.layout.Document(pdf);

            // Đặt font
            PdfFont font = PdfFontFactory.createFont("D:\\spring_boot\\ARIALUNI.TTF", PdfEncodings.IDENTITY_H);

            // Thêm tiêu đề hóa đơn
            document.add(new Paragraph("HÓA ĐƠN THANH TOÁN")
                    .setFont(font)
                    .setFontSize(20)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setBold());
            document.add(new Paragraph("Mã Hóa Đơn: " + txtmahoadon.getText()).setFont(font).setFontSize(12));
            document.add(new Paragraph("Tên Nhân Viên: " + nhanvien.getText()).setFont(font).setFontSize(12));
            document.add(new Paragraph("Địa Chỉ Shop: " + diachi.getText()).setFont(font).setFontSize(12));
            document.add(new Paragraph("Hỗ Trợ Khách Hàng: " + txtemail.getText()).setFont(font).setFontSize(12));
            document.add(new Paragraph("Tên Khách Hàng: " + txthotenkhachhang.getText()).setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("Ngày Tạo Hóa Đơn: " + txtemail.getText()).setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------").setFont(font));

            // Tạo bảng chi tiết sản phẩm
            Table table = new Table(4); // 4 cột: tên sản phẩm, số lượng, giá bán, thành tiền
            table.setWidth(pdf.getDefaultPageSize().getWidth() * 0.9f);

            // Thêm header vào bảng
            table.addHeaderCell(new Paragraph("Tên Sản Phẩm").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
            table.addHeaderCell(new Paragraph("Số Lượng").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
            table.addHeaderCell(new Paragraph("Giá Bán").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
            table.addHeaderCell(new Paragraph("Thành Tiền").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));

            // Biến để tính tổng tiền
            double totalAmount = 0;

            // Duyệt qua danh sách hóa đơn để thêm thông tin vào bảng
            ArrayList<XuatHoaDon> hdList = hd.getAll();
            for (XuatHoaDon order : hdList) {
                double thanhTien = order.getSoLuong() * order.getGiaBan();  // Thành tiền = Số lượng * Giá bán
                totalAmount += thanhTien;  // Cộng dồn vào tổng tiền

                table.addCell(new Paragraph(order.getTenSanPham()).setFont(font));
                table.addCell(new Paragraph(String.valueOf(order.getSoLuong())).setFont(font).setTextAlignment(TextAlignment.CENTER));
                table.addCell(new Paragraph(String.format("%,.0f", order.getGiaBan())).setFont(font).setTextAlignment(TextAlignment.CENTER));
                table.addCell(new Paragraph(String.format("%,.0f", thanhTien)).setFont(font).setTextAlignment(TextAlignment.CENTER));
            }

            document.add(table);
            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------").setFont(font));

            // Tính thuế (10% của tổng tiền)
            double tax = totalAmount * 0.1;  // Thuế = 10% tổng tiền

            // Tính tổng tiền sau thuế
            double totalAmountAfterTax = totalAmount + tax;

            // Thêm thông tin tổng tiền và thuế
            document.add(new Paragraph("TỔNG TIỀN: " + String.format("%,.0f", totalAmount) + " VND")
                    .setFont(font)
                    .setFontSize(12)
                    .setBold()
                    .setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("Thuế (10%): " + String.format("%,.0f", tax) + " VND")
                    .setFont(font)
                    .setFontSize(12)
                    .setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("TỔNG TIỀN SAU THUẾ: " + String.format("%,.0f", totalAmountAfterTax) + " VND")
                    .setFont(font)
                    .setFontSize(12)
                    .setTextAlignment(TextAlignment.RIGHT));
            double tienKhachDua = Double.parseDouble(tienkhachdua.getText().trim().replace(",", ""));
            double tienTraKhach = Double.parseDouble(tientrakhac.getText().trim().replace(",", ""));
            // Thêm các thông tin giảm giá, tiền khách đưa, tiền trả khách
            document.add(new Paragraph("Giảm Giá: " + String.format("%,.0f", Double.parseDouble(giamgia.getText())) + " VND")
                    .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("Tổng Tiền: " + String.format("%,.0f", totalAmountAfterTax - Double.parseDouble(giamgia.getText())) + " VND")
                    .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("Tiền Khách Đưa: " + formatterr.format(tienKhachDua) + " VND")
                    .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("Tiền Trả Khách: " + formatterr.format(tienTraKhach) + " VND")
                    .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));

            // Thông tin ngân hàng và liên hệ
            document.add(new Paragraph("GỬI THANH TOÁN ĐẾN")
                    .setFont(font)
                    .setFontSize(10)
                    .setMarginTop(20));
            document.add(new Paragraph("Số ngân hàng: 0367548754 \nTên ngân hàng: Đoàn Ngọc Duy")
                    .setFont(font)
                    .setFontSize(10));
            document.add(new Paragraph("LIÊN HỆ")
                    .setFont(font)
                    .setFontSize(10)
                    .setMarginTop(-40)
                    .setTextAlignment(TextAlignment.RIGHT));
            document.add(new Paragraph("doanngocduy62@gmail.com\nSĐT: 0382424762")
                    .setFont(font)
                    .setFontSize(10)
                    .setTextAlignment(TextAlignment.RIGHT));

            // Đóng tài liệu
            document.close();
            dispose();
        } catch (IOException e) {
            // Xử lý lỗi khi tạo hóa đơn PDF
            e.printStackTrace();
        }
        // Đường dẫn hình ảnh logo

// String idmaDonHnag = txtid.getText();
//String maDonHang = txtmahoadon.getText();
//String trangThaiHoaDon = "Thanh Toán Thành Công";
//String sql = """
//    UPDATE hoadon
//    SET ngay_lap = GETDATE(), tien_khach_dua = ?, tien_tra_khach = ?, phuong_thuc = ?, trang_thai = ?
//    WHERE ma_hoa_don = ?
//    """;
//String trangThaiDonHang = "Thanh Toán Thành Công";
//String DonHang = txtid.getText();
//String sqlDonHang = """
//    UPDATE donhang
//    SET trang_thai = ?
//    WHERE id_ma_don_hang = ?
//    """;
//try {
//    Connection con = ketnoi.getConnection();
//    PreparedStatement psDonHang = con.prepareStatement(sqlDonHang);
//    psDonHang.setObject(1, trangThaiDonHang);
//    psDonHang.setObject(2, DonHang);
//    int checkDonHang = psDonHang.executeUpdate();
//    double tienKhachDua = Double.parseDouble(tienkhachdua.getText().trim().replace(",", ""));
//    double tienTraKhach = Double.parseDouble(tientrakhac.getText().trim().replace(",", ""));
//    String phuongThuc = phuongthucthanhtoan.getText();
//    PreparedStatement psHoaDon = con.prepareStatement(sql);
//    psHoaDon.setObject(1, tienKhachDua);
//    psHoaDon.setObject(2, tienTraKhach);
//    psHoaDon.setObject(3, phuongThuc);
//    psHoaDon.setObject(4, trangThaiHoaDon);
//    psHoaDon.setObject(5, maDonHang);
//    int checkHoaDon = psHoaDon.executeUpdate();
//    if (checkDonHang > 0 && checkHoaDon > 0) {
//        try {
//    // Tạo file PDF
//    String filePath = "D:\\" + txtmahoadon.getText() + ".pdf";
//    File file = new File(filePath);
//    if (file.exists()) {
//        file.delete();
//    }
//    PdfWriter writer = new PdfWriter(file);
//    PdfDocument pdf = new PdfDocument(writer);
//    com.itextpdf.layout.Document document = new com.itextpdf.layout.Document(pdf);
//    PdfFont font = PdfFontFactory.createFont("D:\\spring_boot\\ARIALUNI.TTF", PdfEncodings.IDENTITY_H);
//    document.add(new Paragraph("HÓA ĐƠN THANH TOÁN")
//            .setFont(font)
//            .setFontSize(20)
//            .setTextAlignment(TextAlignment.CENTER)
//            .setBold());
//    document.add(new Paragraph("Mã Hóa Đơn: " + txtmahoadon.getText()).setFont(font).setFontSize(12));
//    document.add(new Paragraph("Nhân Viên: " + nhanvien.getText()).setFont(font).setFontSize(12));
//    document.add(new Paragraph("Khách Hàng: " + txthotenkhachhang.getText()).setFont(font).setFontSize(12));
//    document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------").setFont(font));
//
//    // Tạo bảng chi tiết sản phẩm
//    Table table = new Table(4); // 4 cột: tên sản phẩm, số lượng, giá bán, thành tiền
//    table.setWidth(pdf.getDefaultPageSize().getWidth() * 0.9f);
//
//    // Thêm header vào bảng
//    table.addHeaderCell(new Paragraph("Tên Sản Phẩm").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
//    table.addHeaderCell(new Paragraph("Số Lượng").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
//    table.addHeaderCell(new Paragraph("Giá Bán").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
//    table.addHeaderCell(new Paragraph("Thành Tiền").setFont(font).setBold().setTextAlignment(TextAlignment.CENTER));
//    double totalAmount = 0;
//    ArrayList<XuatHoaDon> hdList = hd.getAll();
//    for (XuatHoaDon order : hdList) {
//        double thanhTien = order.getSoLuong() * order.getGiaBan();
//        totalAmount += thanhTien;  
//        table.addCell(new Paragraph(order.getTenSanPham()).setFont(font));
//        table.addCell(new Paragraph(String.valueOf(order.getSoLuong())).setFont(font).setTextAlignment(TextAlignment.CENTER));
//        table.addCell(new Paragraph(String.format("%,.0f", order.getGiaBan())).setFont(font).setTextAlignment(TextAlignment.CENTER));
//        table.addCell(new Paragraph(String.format("%,.0f", thanhTien)).setFont(font).setTextAlignment(TextAlignment.CENTER));
//    }
//    document.add(table);
//    document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------").setFont(font));
//    double tax = totalAmount * 0.1; 
//    double totalAmountAfterTax = totalAmount + tax;
//    document.add(new Paragraph("TỔNG TIỀN: " + String.format("%,.0f", totalAmount) + " VND")
//            .setFont(font)
//            .setFontSize(12)
//            .setBold()
//            .setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("Thuế (10%): " + String.format("%,.0f", tax) + " VND")
//            .setFont(font)
//            .setFontSize(12)
//            .setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("TỔNG TIỀN SAU THUẾ: " + String.format("%,.0f", totalAmountAfterTax) + " VND")
//            .setFont(font)
//            .setFontSize(12)
//            .setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("Giảm Giá: " + String.format("%,.0f", Double.parseDouble(giamgia.getText())) + " VND")
//            .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("Tổng Tiền: " + String.format("%,.0f", totalAmountAfterTax - Double.parseDouble(giamgia.getText())) + " VND")
//            .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("Tiền Khách Đưa: " + String.format("%,.0f", Double.parseDouble(tienkhachdua.getText())) + " VND")
//            .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("Tiền Trả Khách: " + String.format("%,.0f", Double.parseDouble(tientrakhac.getText())) + " VND")
//            .setFont(font).setFontSize(12).setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("GỬI THANH TOÁN ĐẾN")
//            .setFont(font)
//            .setFontSize(10)
//            .setMarginTop(20));
//    document.add(new Paragraph("Số ngân hàng: 0367548754 \nTên ngân hàng: Đoàn Ngọc Duy")
//            .setFont(font)
//            .setFontSize(10));
//    document.add(new Paragraph("LIÊN HỆ")
//            .setFont(font)
//            .setFontSize(10)
//            .setMarginTop(-40)
//            .setTextAlignment(TextAlignment.RIGHT));
//    document.add(new Paragraph("doanngocduy62@gmail.com\nSĐT: 0382424762")
//            .setFont(font)
//            .setFontSize(10)
//            .setTextAlignment(TextAlignment.RIGHT));
//    document.close();
//} catch (IOException e) {
//    e.printStackTrace();
//}
//    } else {
//        javax.swing.JOptionPane.showMessageDialog(this, "Thanh Toán Thất Bại");
//    }
//
//} catch (Exception e) {
//    e.printStackTrace();
//}

    }//GEN-LAST:event_XuatHoaDonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idmaDonHnag = txtid.getText();
        String maDonHang = txtmahoadon.getText();
        String trangThaiHoaDon = "Đang Chờ Xác Nhận";
        String sql = """
    UPDATE hoadon
    SET ngay_lap = GETDATE(), tien_khach_dua = ?, tien_tra_khach = ?, phuong_thuc = ?, trang_thai = ?
    WHERE ma_hoa_don = ?
    """;
        String trangThaiDonHang = "Đang Chờ Xác Nhận";
        String DonHang = txtid.getText();
        String sqlDonHang = """
    UPDATE donhang
    SET trang_thai = ?
    WHERE id_ma_don_hang = ?
    """;
        try {
            Connection con = ketnoi.getConnection();
            PreparedStatement psDonHang = con.prepareStatement(sqlDonHang);
            psDonHang.setObject(1, trangThaiDonHang);
            psDonHang.setObject(2, DonHang);
            int checkDonHang = psDonHang.executeUpdate();
            double tienKhachDua = Double.parseDouble(tienkhachdua.getText().trim().replace(",", ""));
            double tienTraKhach = Double.parseDouble(tientrakhac.getText().trim().replace(",", ""));
            String phuongThuc = phuongthucthanhtoan.getText();
            PreparedStatement psHoaDon = con.prepareStatement(sql);
            psHoaDon.setObject(1, tienKhachDua);
            psHoaDon.setObject(2, tienTraKhach);
            psHoaDon.setObject(3, phuongThuc);
            psHoaDon.setObject(4, trangThaiHoaDon);
            psHoaDon.setObject(5, maDonHang);
            int checkHoaDon = psHoaDon.executeUpdate();
            if (checkDonHang > 0 && checkHoaDon > 0) {
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Thanh Toán Thất Bại");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatHoaDonnn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Email;
    private javax.swing.JButton XuatHoaDon;
    private javax.swing.JLabel diachi;
    private javax.swing.JLabel gia;
    private javax.swing.JLabel giamgia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JLabel ngaytao;
    private javax.swing.JLabel nhanvien;
    private javax.swing.JLabel phuongthucthanhtoan;
    private javax.swing.JLabel soluong;
    private javax.swing.JLabel thue;
    private javax.swing.JLabel tienkhachdua;
    private javax.swing.JLabel tientrakhac;
    private javax.swing.JLabel tongtien;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txthotenkhachhang;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtmahoadon;
    private javax.swing.JLabel txtsodienthoaikhachhang;
    private javax.swing.JLabel txttensanpham;
    // End of variables declaration//GEN-END:variables

}
